language: python
python:
  - "3.6.6"
install: 
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script: nosetests  --with-coverage --cover-package=api tests/

after_success:
  - coveralls